<?php

namespace UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\Query
     */
    public function createFindAllQuery()
    {
        return $this->_em->createQuery(
            "
            SELECT user
            FROM UserBundle:User user
            "
        );
    }

    /**
     * @param $id
     * @return \Doctrine\ORM\Query
     */
    public function createFindOneByIdQuery($id)
    {
        $query = $this->_em->createQuery(
            "
            SELECT user
            FROM UserBundle:User user
            WHERE user.id = :id
            "
        );

        $query->setParameter('id', $id);

        return $query;
    }

}
