<?php

namespace UserBundle\Entity\Repository;

use Doctrine\DBAL\Types\Type;
use Doctrine\ORM\EntityRepository;

/**
 * UserVisitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVisitRepository extends EntityRepository
{
    /**
     * @param \Datetime $startDate
     * @param \Datetime $endDate
     * @return \Doctrine\ORM\Query
     */
    public function createDAUQuery($startDate, $endDate)
    {
        $qb = $this->_em->createQueryBuilder();
        return $qb->select($qb->expr()->countDistinct('visit.userId').' as uniqueCount')
            ->from('UserBundle\Entity\UserVisit', 'visit')
            ->andWhere($qb->expr()->between('visit.visitedAt', ':from', ':to'))
            ->setParameter('from', $startDate->format('Y-m-d 00:00:00'))
            ->setParameter('to', $endDate->format('Y-m-d 23:59:59'))
            ->getQuery();
    }
}
